version: '3'

services:
  backend:
    image: simplecolon/nexus-backend:latest
    env_file:
      - ./backend/nexus/.env.prod
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    image: simplecolon/nexus-frontend:latest
    environment:
      - VITE_APP_ENV=production
      - VITE_API_URL_PROD=/api
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
