version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  # backend:
    # Add your backend service configuration here.
    # For example:
    # build:
    #   context: ./path/to/backend
    #   dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    # volumes:
    #   - ./path/to/backend:/app
