from datetime import date, datetime
from typing import Optional
from decimal import Decimal

from pydantic import BaseModel, Field


# 'vendormaster' table in IHMS database
class IHMSTableVendorMaster(BaseModel):
    company_code: str = Field(..., alias="companycode")
    vendor_number: str = Field(..., alias="vendornumber")

    vendor_name: Optional[str] = Field(None, alias="vendorname")
    address1: Optional[str] = None
    address2: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zipcode: Optional[str] = None
    country: Optional[str] = None
    phone_number: Optional[str] = Field(None, alias="phonenumber")
    alpha_sort: Optional[str] = Field(None, alias="alphasort")
    pay_cycle: Optional[str] = Field(None, alias="paycycle")
    opened_date: Optional[date] = None
    last_activity_date: Optional[date] = Field(None, alias="lastactvty_date")
    sub_flag: Optional[str] = Field(None, alias="subflag")
    terms_code: Optional[str] = Field(None, alias="termscode")
    alt_terms_code: Optional[str] = Field(None, alias="alttermscode")
    default_gl_acct: Optional[str] = Field(None, alias="defaultglacct")
    w9_received_flag: Optional[str] = Field(None, alias="w9receivedflag")
    ins_cert_reqd_flag: Optional[str] = Field(None, alias="inscertreqdflag")
    lien_flag: Optional[str] = Field(None, alias="lienflag")
    federal_id_number: Optional[str] = Field(None, alias="federalidnumber")
    form1099_flag: Optional[str] = Field(None, alias="form1099flag")
    group_code: Optional[str] = Field(None, alias="groupcode")
    contact_name: Optional[str] = Field(None, alias="contactname")
    separate_chk_flag: Optional[str] = Field(None, alias="seperatechkflag")
    ins_exp_date: Optional[date] = Field(None, alias="insexp_date")
    wrk_cmp_exp_date: Optional[date] = Field(None, alias="wrkcmpexp_date")
    auto_liab_exp_date: Optional[date] = Field(None, alias="autoliabexp_date")
    excess_exp_date: Optional[date] = Field(None, alias="excessexp_date")
    other_exp_date: Optional[date] = Field(None, alias="otherexp_date")
    fax_number: Optional[str] = Field(None, alias="faxnumber")
    cell_number: Optional[str] = Field(None, alias="cellnumber")
    email_address: Optional[str] = Field(None, alias="emailaddress")
    warranty_email: Optional[str] = None
    accounting_email: Optional[str] = None
    remarks: Optional[str] = None
    pager_number: Optional[str] = Field(None, alias="pagernumber")
    website: Optional[str] = None
    misc1_date: Optional[date] = None
    misc2_date: Optional[date] = None
    misc3_date: Optional[date] = None
    out_of_state: Optional[str] = Field(None, alias="outofstate")
    minority_con: Optional[str] = Field(None, alias="minoritycon")
    print_preference: Optional[str] = Field(None, alias="printpreference")
    field1: Optional[str] = None
    field2: Optional[str] = None
    field3: Optional[str] = None
    field4: Optional[str] = None
    field5: Optional[str] = None
    field6: Optional[str] = None
    inactive: Optional[str] = None
    nhq_flag: Optional[str] = Field(None, alias="nhqflag")
    nhq_hold: Optional[str] = Field(None, alias="nhqhold")
    category_code: Optional[str] = Field(None, alias="categorycode")
    cost_code: Optional[str] = Field(None, alias="costcode")
    name_one_1099: Optional[str] = Field(None, alias="nameone1099")
    name_two_1099: Optional[str] = Field(None, alias="nametwo1099")
    purchases_mtd: Optional[Decimal] = Field(None, alias="purchasesmtd")
    returns_mtd: Optional[Decimal] = Field(None, alias="returnsmtd")
    purchases_ytd: Optional[Decimal] = Field(None, alias="purchasesytd")
    returns_ytd: Optional[Decimal] = Field(None, alias="returnsytd")
    open_balance: Optional[Decimal] = Field(None, alias="openbalance")
    open_retention: Optional[Decimal] = Field(None, alias="openretention")
    number_invoices: Optional[Decimal] = Field(None, alias="numberinvoices")
    repl_ts: Optional[datetime] = None

    class Config:
        populate_by_name = True


# 'udhousemaster' table in IHMS database
class IHMSTableUDHouseMaster(BaseModel):
    company_code: str = Field(..., alias="companycode")
    development_code: str = Field(..., alias="developmentcode")
    house_number: str = Field(..., alias="housenumber")

    punchlist_survey: Optional[str] = Field(None, alias="punchlistsurvey")
    tax_id_no: Optional[str] = Field(None, alias="taxidno")
    phase_num: Optional[str] = Field(None, alias="phasenum")
    spec: Optional[str] = None
    sf_finished: Optional[str] = Field(None, alias="sf_finished")
    sf_unfinished: Optional[str] = Field(None, alias="sf_unfinished")
    sf_porch: Optional[str] = Field(None, alias="sf_porch")
    plans_created_date: Optional[date] = Field(None, alias="planscreateddate")
    drafted_by: Optional[str] = Field(None, alias="draftedby")
    structural_co: Optional[str] = Field(None, alias="structuralco")
    eng_ordered_date: Optional[date] = Field(None, alias="engordereddate")
    eng_recvd_date: Optional[date] = Field(None, alias="engrecvddate")
    plat_ordered_date: Optional[date] = Field(None, alias="platordereddate")
    plat_rec_date: Optional[date] = Field(None, alias="platrecdate")
    arb_submitted: Optional[str] = Field(None, alias="arbsumbitted")
    homesite_rprt_date: Optional[date] = Field(None, alias="homesiterprtdate")
    lslate_change_date: Optional[date] = Field(None, alias="lslatechangedate")
    pm_rev_job_date: Optional[date] = Field(None, alias="pmrevjobdate")
    notes: Optional[str] = None
    evenflow_date: Optional[date] = None
    design: Optional[str] = None
    sales: Optional[str] = None
    spec_date: Optional[date] = None
    spec_cmplt_date: Optional[date] = Field(None, alias="spec_cmplt_date")
    mls: Optional[str] = None
    promo_price: Optional[Decimal] = Field(None, alias="promo_price")
    incentive_notes: Optional[str] = Field(None, alias="incentive_notes")
    projected_cost: Optional[Decimal] = Field(None, alias="projected_cost")
    projection_date: Optional[date] = Field(None, alias="projection_date")
    floor_truss_date: Optional[date] = Field(None, alias="floortrussdate")
    c_release_date: Optional[date] = Field(None, alias="creleasedate")
    initial_jca_date: Optional[date] = Field(None, alias="initialjcadate")
    final_jca_date: Optional[date] = Field(None, alias="finaljcadate")
    est_memo: Optional[str] = Field(None, alias="estmemo")
    budget_adjust: Optional[str] = Field(None, alias="budgetadjust")
    aqt_used: Optional[str] = Field(None, alias="aqt_used")
    aqt_final: Optional[str] = Field(None, alias="aqt_final")
    aqt_report_date: Optional[date] = Field(None, alias="aqt_report_date")
    aqt_report_f_date: Optional[date] = Field(None, alias="aqtreport_f_date")
    var_fig_sent_date: Optional[date] = Field(None, alias="varfigsentdate")
    var_fig_update: Optional[date] = Field(None, alias="varfigupdate")
    qal_load_date: Optional[date] = Field(None, alias="qalloaddate")
    repl_ts: Optional[datetime] = None

    class Config:
        populate_by_name = True


# 'devmaster' table in IHMS database
class IHMSTableDevMaster(BaseModel):
    companycode: str = Field(..., alias="companycode")
    developmentcode: str = Field(..., alias="developmentcode")

    description: Optional[str] = Field(None, alias="description")
    divisioncode: Optional[str] = Field(None, alias="divisioncode")
    inactive: Optional[str] = Field(None, alias="inactive")
    superintendent: Optional[str] = Field(None, alias="superintendent")
    superaddress1: Optional[str] = Field(None, alias="superaddress1")
    superaddress2: Optional[str] = Field(None, alias="superaddress2")
    supercity: Optional[str] = Field(None, alias="supercity")
    superstate: Optional[str] = Field(None, alias="superstate")
    superzip: Optional[str] = Field(None, alias="superzip")
    supercountry: Optional[str] = Field(None, alias="supercountry")
    superphone1: Optional[str] = Field(None, alias="superphone1")
    superphone2: Optional[str] = Field(None, alias="superphone2")
    superfax: Optional[str] = Field(None, alias="superfax")
    superpager: Optional[str] = Field(None, alias="superpager")
    supercell: Optional[str] = Field(None, alias="supercell")
    superemail: Optional[str] = Field(None, alias="superemail")
    salesmanager: Optional[str] = Field(None, alias="salesmanager")
    salesaddress1: Optional[str] = Field(None, alias="salesaddress1")
    salesaddress2: Optional[str] = Field(None, alias="salesaddress2")
    salescity: Optional[str] = Field(None, alias="salescity")
    salesstate: Optional[str] = Field(None, alias="salesstate")
    saleszip: Optional[str] = Field(None, alias="saleszip")
    salescountry: Optional[str] = Field(None, alias="salescountry")
    salesphone1: Optional[str] = Field(None, alias="salesphone1")
    salesphone2: Optional[str] = Field(None, alias="salesphone2")
    salesfax: Optional[str] = Field(None, alias="salesfax")
    salespager: Optional[str] = Field(None, alias="salespager")
    salescell: Optional[str] = Field(None, alias="salescell")
    salesemail: Optional[str] = Field(None, alias="salesemail")
    ccsalesemails: Optional[str] = Field(None, alias="ccsalesemails")
    salespreappemail: Optional[str] = Field(None, alias="salespreappemail")
    ccsalespreapp: Optional[str] = Field(None, alias="ccsalespreapp")
    purchaseprimary: Optional[str] = Field(None, alias="purchaseprimary")
    purchasephone: Optional[str] = Field(None, alias="purchasephone")
    purchasefax: Optional[str] = Field(None, alias="purchasefax")
    purchasecell: Optional[str] = Field(None, alias="purchasecell")
    purchaseemail: Optional[str] = Field(None, alias="purchaseemail")
    ccpurchaseemails: Optional[str] = Field(None, alias="ccpurchaseemails")
    salesbitmap: Optional[str] = Field(None, alias="salesbitmap")
    warrantymanager: Optional[str] = Field(None, alias="warrantymanager")
    warrantyaddress1: Optional[str] = Field(None, alias="warrantyaddress1")
    warrantyaddress2: Optional[str] = Field(None, alias="warrantyaddress2")
    warrantycity: Optional[str] = Field(None, alias="warrantycity")
    warrantystate: Optional[str] = Field(None, alias="warrantystate")
    warrantyzip: Optional[str] = Field(None, alias="warrantyzip")
    warrantycountry: Optional[str] = Field(None, alias="warrantycountry")
    warrantyphone1: Optional[str] = Field(None, alias="warrantyphone1")
    warrantyphone2: Optional[str] = Field(None, alias="warrantyphone2")
    warrantyfax: Optional[str] = Field(None, alias="warrantyfax")
    warrantypager: Optional[str] = Field(None, alias="warrantypager")
    warrantycell: Optional[str] = Field(None, alias="warrantycell")
    warrantyemail: Optional[str] = Field(None, alias="warrantyemail")
    sonotifyflag: Optional[str] = Field(None, alias="sonotifyflag")
    unused: Optional[str] = Field(None, alias="unused")
    itkpublish: Optional[str] = Field(None, alias="itkpublish")
    itkprospectmail: Optional[str] = Field(None, alias="itkprospectmail")
    execemail: Optional[str] = Field(None, alias="execemail")
    basedeppercent: Optional[Decimal] = Field(None, alias="basedeppercent")
    optiondeppercent: Optional[Decimal] = Field(None, alias="optiondeppercent")
    salestaxpercent: Optional[Decimal] = Field(None, alias="salestaxpercent")
    parentco: Optional[str] = Field(None, alias="parentco")
    parentdev: Optional[str] = Field(None, alias="parentdev")
    contractparentco: Optional[str] = Field(None, alias="contractparentco")
    contractparentde: Optional[str] = Field(None, alias="contractparentde")
    projectmgr: Optional[str] = Field(None, alias="projectmgr")
    repl_ts: Optional[datetime] = Field(None, alias="repl_ts")

    class Config:
        populate_by_name = True


# 'housemaster' table in IHMS database
class IHMSTableHouseMaster(BaseModel):
    companycode: str = Field(..., alias="companycode")
    developmentcode: str = Field(..., alias="developmentcode")
    housenumber: str = Field(..., alias="housenumber")

    modelcode: Optional[str] = Field(None, alias="modelcode")
    elevationcode: Optional[str] = Field(None, alias="elevationcode")
    remarks: Optional[str] = Field(None, alias="remarks")
    blocknumber: Optional[str] = Field(None, alias="blocknumber")
    lotnumber: Optional[str] = Field(None, alias="lotnumber")
    comments: Optional[str] = Field(None, alias="comments")
    release_date: Optional[date] = Field(None, alias="release_date")
    jionumber: Optional[str] = Field(None, alias="jionumber")
    unused: Optional[str] = Field(None, alias="unused")
    currentjobstart: Optional[str] = Field(None, alias="currentjobstart")
    lastjobstart: Optional[str] = Field(None, alias="lastjobstart")
    buyername: Optional[str] = Field(None, alias="buyername")
    settlement_date: Optional[date] = Field(None, alias="settlement_date")
    deposit_date: Optional[date] = Field(None, alias="deposit_date")
    misc1_date: Optional[date] = Field(None, alias="misc1_date")
    unused_2: Optional[str] = Field(None, alias="unused_2")
    financing_type: Optional[str] = Field(None, alias="financing_type")
    misc2_date: Optional[date] = Field(None, alias="misc2_date")
    misc3_date: Optional[date] = Field(None, alias="misc3_date")
    costflag: Optional[str] = Field(None, alias="costflag")
    salesreleasedate: Optional[date] = Field(None, alias="salesreleasedate")
    contract_date: Optional[date] = Field(None, alias="contract_date")
    ratified_date: Optional[date] = Field(None, alias="ratified_date")
    building_num: Optional[str] = Field(None, alias="building_num")
    cntrk_submt_date: Optional[date] = Field(None, alias="cntrk_submt_date")
    homephone: Optional[str] = Field(None, alias="homephone")
    workphone: Optional[str] = Field(None, alias="workphone")
    option_incv_amt: Optional[Decimal] = Field(None, alias="option_incv_amt")
    closing_incv_amt: Optional[Decimal] = Field(None, alias="closing_incv_amt")
    points_incv_amt: Optional[Decimal] = Field(None, alias="points_incv_amt")
    coop_amount: Optional[Decimal] = Field(None, alias="coop_amount")
    permitnumber: Optional[str] = Field(None, alias="permitnumber")
    coop_yn: Optional[str] = Field(None, alias="coop_yn")
    unused_3: Optional[str] = Field(None, alias="unused_3")
    orientation: Optional[str] = Field(None, alias="orientation")
    loan_num: Optional[str] = Field(None, alias="loan_num")
    warrantypolicy: Optional[str] = Field(None, alias="warrantypolicy")
    address1: Optional[str] = Field(None, alias="address1")
    address2: Optional[str] = Field(None, alias="address2")
    address3: Optional[str] = Field(None, alias="address3")
    warranty_date: Optional[date] = Field(None, alias="warranty_date")
    unpackedhousenum: Optional[str] = Field(None, alias="unpackedhousenum")
    misc4_date: Optional[date] = Field(None, alias="misc4_date")
    broker_amount: Optional[Decimal] = Field(None, alias="broker_amount")
    misc5_date: Optional[date] = Field(None, alias="misc5_date")
    misc6_date: Optional[date] = Field(None, alias="misc6_date")
    misc7_date: Optional[date] = Field(None, alias="misc7_date")
    unused2: Optional[str] = Field(None, alias="unused2")
    upgradeprice: Optional[Decimal] = Field(None, alias="upgradeprice")
    agentcode: Optional[str] = Field(None, alias="agentcode")
    brokercode: Optional[str] = Field(None, alias="brokercode")
    coop_name: Optional[str] = Field(None, alias="coop_name")
    house_type: Optional[str] = Field(None, alias="house_type")
    broker_pct: Optional[Decimal] = Field(None, alias="broker_pct")
    lst_chgord_num: Optional[str] = Field(None, alias="lst_chgord_num")
    misc8_date: Optional[date] = Field(None, alias="misc8_date")
    permit_date: Optional[date] = Field(None, alias="permit_date")
    pvc8: Optional[str] = Field(None, alias="pvc8")
    deposit_due: Optional[Decimal] = Field(None, alias="deposit_due")
    est_base_price: Optional[Decimal] = Field(None, alias="est_base_price")
    est_options_prc: Optional[Decimal] = Field(None, alias="est_options_prc")
    est_lot_premium: Optional[Decimal] = Field(None, alias="est_lot_premium")
    salesmancode: Optional[str] = Field(None, alias="salesmancode")
    title_co: Optional[str] = Field(None, alias="title_co")
    mtg_prequal_date: Optional[date] = Field(None, alias="mtg_prequal_date")
    aosacceptedflag: Optional[str] = Field(None, alias="aosacceptedflag")
    est_upgrade_prc: Optional[Decimal] = Field(None, alias="est_upgrade_prc")
    releasenum: Optional[str] = Field(None, alias="releasenum")
    coop_agent_addr1: Optional[str] = Field(None, alias="coop_agent_addr1")
    coop_agent_addr2: Optional[str] = Field(None, alias="coop_agent_addr2")
    not_used_2: Optional[str] = Field(None, alias="not_used_2")
    estsettl_date: Optional[date] = Field(None, alias="estsettl_date")
    misc9_date: Optional[date] = Field(None, alias="misc9_date")
    walk_thru_date: Optional[date] = Field(None, alias="walk_thru_date")
    mtg_approv_date: Optional[date] = Field(None, alias="mtg_approv_date")
    postage: Optional[str] = Field(None, alias="postage")
    walk_thru_time: Optional[str] = Field(None, alias="walk_thru_time")
    am_pm: Optional[str] = Field(None, alias="am_pm")
    unused4: Optional[str] = Field(None, alias="unused4")
    conststart_date: Optional[date] = Field(None, alias="conststart_date")
    lothold: Optional[str] = Field(None, alias="lothold")
    mtg_applied_date: Optional[date] = Field(None, alias="mtg_applied_date")
    misc10_date: Optional[date] = Field(None, alias="misc10_date")
    wostage: Optional[str] = Field(None, alias="wostage")
    misc11_date: Optional[date] = Field(None, alias="misc11_date")
    misc12_date: Optional[date] = Field(None, alias="misc12_date")
    misc1_field: Optional[str] = Field(None, alias="misc1_field")
    misc2_field: Optional[str] = Field(None, alias="misc2_field")
    buyersname1: Optional[str] = Field(None, alias="buyersname1")
    buyersname2: Optional[str] = Field(None, alias="buyersname2")
    buyersname3: Optional[str] = Field(None, alias="buyersname3")
    previousaddress1: Optional[str] = Field(None, alias="previousaddress1")
    previousaddress2: Optional[str] = Field(None, alias="previousaddress2")
    promissorynote1: Optional[str] = Field(None, alias="promissorynote1")
    promissorynote2: Optional[str] = Field(None, alias="promissorynote2")
    promissory1date: Optional[date] = Field(None, alias="promissory1date")
    promissory2date: Optional[date] = Field(None, alias="promissory2date")
    promissoryamt1: Optional[Decimal] = Field(None, alias="promissoryamt1")
    promissoryamt2: Optional[Decimal] = Field(None, alias="promissoryamt2")
    pvc: Optional[str] = Field(None, alias="pvc")
    warrantycomments: Optional[str] = Field(None, alias="warrantycomments")
    promissorynote3: Optional[str] = Field(None, alias="promissorynote3")
    promissory3date: Optional[date] = Field(None, alias="promissory3date")
    promissoryamt3: Optional[Decimal] = Field(None, alias="promissoryamt3")
    depositamtpaid: Optional[str] = Field(None, alias="depositamtpaid")
    ins1_date: Optional[date] = Field(None, alias="ins1_date")
    ins2_date: Optional[date] = Field(None, alias="ins2_date")
    ins3_date: Optional[date] = Field(None, alias="ins3_date")
    ins4_date: Optional[date] = Field(None, alias="ins4_date")
    ins5_date: Optional[date] = Field(None, alias="ins5_date")
    pctcompl: Optional[str] = Field(None, alias="pctcompl")
    pvc1: Optional[str] = Field(None, alias="pvc1")
    casenumber: Optional[str] = Field(None, alias="casenumber")
    lotcontractdate: Optional[date] = Field(None, alias="lotcontractdate")
    lotratifydate: Optional[date] = Field(None, alias="lotratifydate")
    lotsettledate: Optional[date] = Field(None, alias="lotsettledate")
    specflag: Optional[str] = Field(None, alias="specflag")
    housetaxenable: Optional[str] = Field(None, alias="housetaxenable")
    cellphone: Optional[str] = Field(None, alias="cellphone")
    email: Optional[str] = Field(None, alias="email")
    superuserid: Optional[str] = Field(None, alias="superuserid")
    swornstatement: Optional[str] = Field(None, alias="swornstatement")
    housetaxpercent: Optional[Decimal] = Field(None, alias="housetaxpercent")
    baseprice: Optional[Decimal] = Field(None, alias="baseprice")
    optionsprice: Optional[Decimal] = Field(None, alias="optionsprice")
    lotpremium: Optional[Decimal] = Field(None, alias="lotpremium")
    not_used_6: Optional[Decimal] = Field(None, alias="not_used_6")
    depositamount: Optional[Decimal] = Field(None, alias="depositamount")
    mortgage_amount: Optional[Decimal] = Field(None, alias="mortgage_amount")
    fee_pct: Optional[Decimal] = Field(None, alias="fee_pct")
    points_code: Optional[Decimal] = Field(None, alias="points_code")
    constr_loan_amt: Optional[Decimal] = Field(None, alias="constr_loan_amt")
    pct_of_blding: Optional[Decimal] = Field(None, alias="pct_of_blding")
    repl_ts: Optional[datetime] = Field(None, alias="repl_ts")

    class Config:
        populate_by_name = True


# Shape of IHMS entire house data
class IHMSHouseData(BaseModel):
    company_code: Optional[str] = Field(None, alias="COMPANYCODE")
    development_code: Optional[str] = Field(None, alias="DEVELOPMENTCODE")
    house_number: Optional[str] = Field(None, alias="HOUSENUMBER")
    model_code: Optional[str] = Field(None, alias="MODELCODE")
    elevation_code: Optional[str] = Field(None, alias="ELEVATIONCODE")
    remarks: Optional[str] = Field(None, alias="REMARKS")
    block_number: Optional[str] = Field(None, alias="BLOCKNUMBER")
    lot_number: Optional[str] = Field(None, alias="LOTNUMBER")
    comments: Optional[str] = Field(None, alias="COMMENTS")
    jio_number: Optional[str] = Field(None, alias="JIONUMBER")
    unused: Optional[str] = Field(None, alias="UNUSED")
    current_job_start: Optional[str] = Field(None, alias="CURRENTJOBSTART")
    last_job_start: Optional[str] = Field(None, alias="LASTJOBSTART")
    buyer_name: Optional[str] = Field(None, alias="BUYERNAME")
    unused_2: Optional[str] = Field(None, alias="UNUSED_2")
    financing_type: Optional[str] = Field(None, alias="FINANCING_TYPE")
    cost_flag: Optional[str] = Field(None, alias="COSTFLAG")
    building_num: Optional[str] = Field(None, alias="BUILDING_NUM")
    home_phone: Optional[str] = Field(None, alias="HOMEPHONE")
    work_phone: Optional[str] = Field(None, alias="WORKPHONE")
    option_incv_amt: Optional[float] = Field(None, alias="OPTION_INCV_AMT")
    closing_incv_amt: Optional[float] = Field(None, alias="CLOSING_INCV_AMT")
    points_incv_amt: Optional[float] = Field(None, alias="POINTS_INCV_AMT")
    coop_amount: Optional[float] = Field(None, alias="COOP_AMOUNT")
    permit_number: Optional[str] = Field(None, alias="PERMITNUMBER")
    coop_yn: Optional[str] = Field(None, alias="COOP_YN")
    unused_3: Optional[str] = Field(None, alias="UNUSED_3")
    orientation: Optional[str] = Field(None, alias="ORIENTATION")
    loan_num: Optional[str] = Field(None, alias="LOAN_NUM")
    warranty_policy: Optional[str] = Field(None, alias="WARRANTYPOLICY")
    address1: Optional[str] = Field(None, alias="ADDRESS1")
    address2: Optional[str] = Field(None, alias="ADDRESS2")
    address3: Optional[str] = Field(None, alias="ADDRESS3")
    unpacked_house_num: Optional[str] = Field(None, alias="UNPACKEDHOUSENUM")
    broker_amount: Optional[float] = Field(None, alias="BROKER_AMOUNT")
    unused2: Optional[str] = Field(None, alias="UNUSED2")
    upgrade_price: Optional[float] = Field(None, alias="UPGRADEPRICE")
    agent_code: Optional[str] = Field(None, alias="AGENTCODE")
    broker_code: Optional[str] = Field(None, alias="BROKERCODE")
    coop_name: Optional[str] = Field(None, alias="COOP_NAME")
    house_type: Optional[str] = Field(None, alias="HOUSE_TYPE")
    broker_pct: Optional[float] = Field(None, alias="BROKER_PCT")
    lst_chgord_num: Optional[str] = Field(None, alias="LST_CHGORD_NUM")
    pvc8: Optional[str] = Field(None, alias="PVC8")
    deposit_due: Optional[float] = Field(None, alias="DEPOSIT_DUE")
    est_base_price: Optional[float] = Field(None, alias="EST_BASE_PRICE")
    est_options_prc: Optional[float] = Field(None, alias="EST_OPTIONS_PRC")
    est_lot_premium: Optional[float] = Field(None, alias="EST_LOT_PREMIUM")
    salesman_code: Optional[str] = Field(None, alias="SALESMANCODE")
    title_co: Optional[str] = Field(None, alias="TITLE_CO")
    aos_accepted_flag: Optional[str] = Field(None, alias="AOSACCEPTEDFLAG")
    est_upgrade_prc: Optional[float] = Field(None, alias="EST_UPGRADE_PRC")
    release_num: Optional[str] = Field(None, alias="RELEASENUM")
    coop_agent_addr1: Optional[str] = Field(None, alias="COOP_AGENT_ADDR1")
    coop_agent_addr2: Optional[str] = Field(None, alias="COOP_AGENT_ADDR2")
    not_used_2: Optional[str] = Field(None, alias="NOT_USED_2")
    postage: Optional[str] = Field(None, alias="POSTAGE")
    walk_thru_time: Optional[str] = Field(None, alias="WALK_THRU_TIME")
    am_pm: Optional[str] = Field(None, alias="AM_PM")
    unused4: Optional[str] = Field(None, alias="UNUSED4")
    lothold: Optional[str] = Field(None, alias="LOTHOLD")
    wostage: Optional[str] = Field(None, alias="WOSTAGE")
    misc1_field: Optional[str] = Field(None, alias="MISC1_FIELD")
    misc2_field: Optional[str] = Field(None, alias="MISC2_FIELD")
    buyers_name1: Optional[str] = Field(None, alias="BUYERSNAME1")
    buyers_name2: Optional[str] = Field(None, alias="BUYERSNAME2")
    buyers_name3: Optional[str] = Field(None, alias="BUYERSNAME3")
    previous_address1: Optional[str] = Field(None, alias="PREVIOUSADDRESS1")
    previous_address2: Optional[str] = Field(None, alias="PREVIOUSADDRESS2")
    promissory_note1: Optional[str] = Field(None, alias="PROMISSORYNOTE1")
    promissory_note2: Optional[str] = Field(None, alias="PROMISSORYNOTE2")
    promissory_amt1: Optional[float] = Field(None, alias="PROMISSORYAMT1")
    promissory_amt2: Optional[float] = Field(None, alias="PROMISSORYAMT2")
    pvc: Optional[str] = Field(None, alias="PVC")
    warranty_comments: Optional[str] = Field(None, alias="WARRANTYCOMMENTS")
    promissory_note3: Optional[str] = Field(None, alias="PROMISSORYNOTE3")
    promissory_amt3: Optional[float] = Field(None, alias="PROMISSORYAMT3")
    deposit_amt_paid: Optional[str] = Field(None, alias="DEPOSITAMTPAID")
    pct_compl: Optional[str] = Field(None, alias="PCTCOMPL")
    pvc1: Optional[str] = Field(None, alias="PVC1")
    case_number: Optional[str] = Field(None, alias="CASENUMBER")
    spec_flag: Optional[str] = Field(None, alias="SPECFLAG")
    house_tax_enable: Optional[str] = Field(None, alias="HOUSETAXENABLE")
    cellphone: Optional[str] = Field(None, alias="CELLPHONE")
    email: Optional[str] = Field(None, alias="EMAIL")
    super_user_id: Optional[str] = Field(None, alias="SUPERUSERID")
    sworn_statement: Optional[str] = Field(None, alias="SWORNSTATEMENT")
    terminator: Optional[str] = Field(None, alias="TERMINATOR")
    house_tax_percent: Optional[float] = Field(None, alias="HOUSETAXPERCENT")
    base_price: Optional[float] = Field(None, alias="BASEPRICE")
    options_price: Optional[float] = Field(None, alias="OPTIONSPRICE")
    lot_premium: Optional[float] = Field(None, alias="LOTPREMIUM")
    deposit_amount: Optional[float] = Field(None, alias="DEPOSITAMOUNT")
    mortgage_amount: Optional[float] = Field(None, alias="MORTGAGE_AMOUNT")
    fee_pct: Optional[float] = Field(None, alias="FEE_PCT")
    points_code: Optional[float] = Field(None, alias="POINTS_CODE")
    constr_loan_amt: Optional[float] = Field(None, alias="CONSTR_LOAN_AMT")
    pct_of_blding: Optional[float] = Field(None, alias="PCT_OF_BLDING")
    companycode_138: Optional[str] = Field(None, alias="COMPANYCODE_138")
    developmentcode_139: Optional[str] = Field(None, alias="DEVELOPMENTCODE_139")
    housenumber_140: Optional[str] = Field(None, alias="HOUSENUMBER_140")
    punchlist_survey: Optional[str] = Field(None, alias="PUNCHLISTSURVEY")
    taxid_no: Optional[str] = Field(None, alias="TAXIDNO")
    phase_num: Optional[str] = Field(None, alias="PHASENUM")
    spec: Optional[str] = Field(None, alias="SPEC")
    sf_finished: Optional[str] = Field(None, alias="SF_FINISHED")
    sf_unfinished: Optional[str] = Field(None, alias="SF_UNFINISHED")
    sf_porch: Optional[str] = Field(None, alias="SF_PORCH")
    drafted_by: Optional[str] = Field(None, alias="DRAFTEDBY")
    structural_co: Optional[str] = Field(None, alias="STRUCTURALCO")
    arb_submitted: Optional[str] = Field(None, alias="ARBSUMBITTED")
    notes: Optional[str] = Field(None, alias="NOTES")
    design: Optional[str] = Field(None, alias="DESIGN")
    sales: Optional[str] = Field(None, alias="SALES")
    mls: Optional[str] = Field(None, alias="MLS")
    promo_price: Optional[float] = Field(None, alias="PROMO_PRICE")
    incentive_notes: Optional[str] = Field(None, alias="INCENTIVE_NOTES")
    projected_cost: Optional[float] = Field(None, alias="PROJECTED_COST")
    estmemo: Optional[str] = Field(None, alias="ESTMEMO")
    budget_adjust: Optional[str] = Field(None, alias="BUDGETADJUST")
    aqt_used: Optional[str] = Field(None, alias="AQT_USED")
    aqt_final: Optional[str] = Field(None, alias="AQT_FINAL")
    mtg_approv_date: Optional[str] = Field(None, alias="MTG_APPROV_DATE")
    settlement_date: Optional[str] = Field(None, alias="SETTLEMENT_DATE")
    misc8_date: Optional[str] = Field(None, alias="MISC8_DATE")
    homesite_prt_date: Optional[str] = Field(None, alias="HOMESITERPRTDATE")
    misc2_date: Optional[str] = Field(None, alias="MISC2_DATE")
    aqtreport_f_date: Optional[str] = Field(None, alias="AQTREPORT_F_DATE")
    permit_date: Optional[str] = Field(None, alias="PERMIT_DATE")
    lslate_change_date: Optional[str] = Field(None, alias="LSLATECHANGEDATE")
    varfig_update: Optional[str] = Field(None, alias="VARFIGUPDATE")
    misc3_date: Optional[str] = Field(None, alias="MISC3_DATE")
    misc9_date: Optional[str] = Field(None, alias="MISC9_DATE")
    eng_recvd_date: Optional[str] = Field(None, alias="ENGRECVDDATE")
    mtg_prequal_date: Optional[str] = Field(None, alias="MTG_PREQUAL_DATE")
    plat_ordered_date: Optional[str] = Field(None, alias="PLATORDEREDDATE")
    floor_truss_date: Optional[str] = Field(None, alias="FLOORTRUSSDATE")
    ratified_date: Optional[str] = Field(None, alias="RATIFIED_DATE")
    evenflow_date: Optional[str] = Field(None, alias="EVENFLOW_DATE")
    pmrev_job_date: Optional[str] = Field(None, alias="PMREVJOBDATE")
    ins3_date: Optional[str] = Field(None, alias="INS3_DATE")
    mtg_applied_date: Optional[str] = Field(None, alias="MTG_APPLIED_DATE")
    initial_jca_date: Optional[str] = Field(None, alias="INITIALJCADATE")
    misc7_date: Optional[str] = Field(None, alias="MISC7_DATE")
    misc4_date: Optional[str] = Field(None, alias="MISC4_DATE")
    release_date: Optional[str] = Field(None, alias="RELEASE_DATE")
    eng_ordered_date: Optional[str] = Field(None, alias="ENGORDEREDDATE")
    misc12_date: Optional[str] = Field(None, alias="MISC12_DATE")
    final_jca_date: Optional[str] = Field(None, alias="FINALJCADATE")
    warranty_date: Optional[str] = Field(None, alias="WARRANTY_DATE")
    misc1_date: Optional[str] = Field(None, alias="MISC1_DATE")
    const_start_date: Optional[str] = Field(None, alias="CONSTSTART_DATE")
    varfig_sent_date: Optional[str] = Field(None, alias="VARFIGSENTDATE")
    misc10_date: Optional[str] = Field(None, alias="MISC10_DATE")
    misc5_date: Optional[str] = Field(None, alias="MISC5_DATE")
    promissory1_date: Optional[str] = Field(None, alias="PROMISSORY1DATE")
    walk_thru_date: Optional[str] = Field(None, alias="WALK_THRU_DATE")
    qal_load_date: Optional[str] = Field(None, alias="QALLOADDATE")
    lot_contract_date: Optional[str] = Field(None, alias="LOTCONTRACTDATE")
    contract_date: Optional[str] = Field(None, alias="CONTRACT_DATE")
    ins5_date: Optional[str] = Field(None, alias="INS5_DATE")
    est_settl_date: Optional[str] = Field(None, alias="ESTSETTL_DATE")
    plans_created_date: Optional[str] = Field(None, alias="PLANSCREATEDDATE")
    plat_rec_date: Optional[str] = Field(None, alias="PLATRECDATE")
    misc6_date: Optional[str] = Field(None, alias="MISC6_DATE")
    misc11_date: Optional[str] = Field(None, alias="MISC11_DATE")
    crelease_date: Optional[str] = Field(None, alias="CRELEASEDATE")
    lot_settle_date: Optional[str] = Field(None, alias="LOTSETTLEDATE")
    promissory3_date: Optional[str] = Field(None, alias="PROMISSORY3DATE")


# Fields from IHMS House Data, that EPC cares about
class IHMSFilteredHouseData(BaseModel):
    ## Lot Info
    house_number: Optional[str] = Field(None, alias="HOUSENUMBER")
    # contract date
    contract_date: Optional[str] = Field(None, alias="CONTRACT_DATE")
    # community
    development_code: Optional[str] = Field(None, alias="DEVELOPMENTCODE")
    # section
    block_number: Optional[str] = Field(None, alias="BLOCKNUMBER")
    # lot number
    lot_number: Optional[str] = Field(None, alias="LOTNUMBER")
    # product
    model_code: Optional[str] = Field(None, alias="MODELCODE")
    # elevation
    elevation_code: Optional[str] = Field(None, alias="ELEVATIONCODE")
    # superintedant
    super_user_id: Optional[str] = Field(None, alias="SUPERUSERID")

    ## Drafting
    # Drafter
    drafted_by: Optional[str] = Field(None, alias="DRAFTEDBY")
    # Assigned On (just show the life style completed date)
    lslate_change_date: Optional[str] = Field(None, alias="LSLATECHANGEDATE")

    ## Engineering
    # Engineer
    structural_co: Optional[str] = Field(None, alias="STRUCTURALCO")
    # Sent On
    eng_ordered_date: Optional[str] = Field(None, alias="ENGORDEREDDATE")
    # Received On
    eng_recvd_date: Optional[str] = Field(None, alias="ENGRECVDDATE")

    ## Plat
    plat_ordered_date: Optional[str] = Field(None, alias="PLATORDEREDDATE")
    plat_rec_date: Optional[str] = Field(None, alias="PLATRECDATE")

    ## Permitting
    permit_number: Optional[str] = Field(None, alias="PERMITNUMBER")
    permit_date: Optional[str] = Field(None, alias="PERMIT_DATE")

    ## Notes
    remarks: Optional[str] = Field(None, alias="REMARKS")
    notes: Optional[str] = Field(None, alias="NOTES")
    comments: Optional[str] = Field(None, alias="COMMENTS")

    ## BuildByPlans
    const_start_date: Optional[str] = Field(None, alias="CONSTSTART_DATE")
